### ISSUE TITLE
events missing

### ISSUE THREAD

**Issue by ali-habibzadeh** [nnnnathann/angular-panhandler#17]
Is it possible to listen to for example:

onPanStart
onPanEnds
onHorizontalPanReachedEnd
etc... ?

**Comment by nnnnathann** [comment]
This is currently not emitting events, but that sounds like a nice thing to have! Definitely would be open to having those in here.

Not familiar with the events idioms in angular, how would you expect to register callbacks?

**Comment by ali-habibzadeh** [comment]
I would add them as attributes. <div panhandler on-horizontal-end="myHorizontalEndHandler($event)"

and then you grab them using attr.onHorizontalEnd()
